rabbitmq:
  image: rabbitmq:3.6.5-management
  hostname: rabitmqhost
  ports:
    - 15672:15672
    - 5672:5672
  volumes:
    - "./rabbitmq_plugins:/etc/rabbitmq/enabled_plugins"
    - "./WebApp/data.sqlite:/app/data.sqlite"
   # - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
ModbusServer:
  image: bentou/michalmodbus
  ports:
    - 80:5000
  volumes:
    - "./webapp.config:/app/webapp.config"
  build:
    - "./WebApp"

