rabbitmq:
  image: rabbitmq:3.6.5-management
  hostname: rabitmqhost
  ports:
    - 8080:15672
    - 5672:5672
  volumes:
    - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
    - "./../../rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
ModbusServer:
  image: bentou/michalmodbus
  ports:
    - 80:5000